# Generated by Django 5.0 on 2024-01-02 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msestocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockdata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='msestocks.stock'),
        ),
    ]
