# Generated by Django 5.0 on 2024-01-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('precent_change', models.FloatField()),
                ('volume', models.IntegerField()),
                ('turnover', models.FloatField()),
            ],
        ),
    ]
