# Generated by Django 5.0 on 2024-01-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msestocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='precent_change',
            new_name='precentchange',
        ),
    ]
