# Generated by Django 5.0 on 2024-01-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msestocks', '0003_rename_precentchange_stock_precent_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='precent_change',
            new_name='percent_change',
        ),
    ]
