# Generated by Django 5.0 on 2024-01-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msestocks', '0005_stock_close_price_stock_open_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
