# Generated by Django 5.0 on 2024-01-01 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msestocks', '0006_remove_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open_price',
            field=models.FloatField(),
        ),
    ]
