# Generated by Django 5.0 on 2024-01-01 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msestocks', '0007_stock_timestamp_alter_stock_close_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='close_price',
            new_name='current_close_price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='open_price',
            new_name='current_open_price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='turnover',
            new_name='current_turnover',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='volume',
            new_name='current_volume',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='HistoricalStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('percent_change', models.FloatField()),
                ('volume', models.IntegerField()),
                ('turnover', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msestocks.stock')),
            ],
        ),
    ]
